### ISSUE TITLE
error when primary key type is not int

### ISSUE THREAD

**Issue by zhenglisai** [demon-bixia/django-api-admin#5]
", line 51, in get
    'object_id': int(item['pk'])}, request=request)
ValueError: invalid literal for int() with base 10: '3f7258fdd8678efd70a98c3624f640d0'

**Comment by zhenglisai** [comment]
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/django_api_admin/views/admin_views.py", line 51, in get
    'object_id': int(item['pk'])}, request=request)

i delete the int transform, and the code works

**Comment by demon-bixia** [comment]
your correct there shouldn't be any int transform here since pk's can be uuid.
